"""
前端配置模块
Frontend Configuration Package
"""

from .settings import (
    REQUEST_TIMEOUT_ANSWER,
    REQUEST_TIMEOUT_INGEST,
    REQUEST_TIMEOUT_STATS,
    REGION_OPTIONS,
    CATEGORY_OPTIONS,
    SEARCH_MODE_OPTIONS,
    DEFAULT_API_URL,
    SUPPORTED_FILE_TYPES,
    PAGE_SIZE_OPTIONS,
    DIFFICULTY_OPTIONS,
    EVALUATION_TYPES,
)

__all__ = [
    "REQUEST_TIMEOUT_ANSWER",
    "REQUEST_TIMEOUT_INGEST",
    "REQUEST_TIMEOUT_STATS",
    "REGION_OPTIONS",
    "CATEGORY_OPTIONS",
    "SEARCH_MODE_OPTIONS",
    "DEFAULT_API_URL",
    "SUPPORTED_FILE_TYPES",
    "PAGE_SIZE_OPTIONS",
    "DIFFICULTY_OPTIONS",
    "EVALUATION_TYPES",
]
