"""
工具模块
Utilities Package
"""

from .session import (
    init_session_state,
    save_tokens,
    save_user_info,
    clear_auth,
    set_current_page,
    is_authenticated,
    get_api_url,
    set_api_url,
    add_qa_history,
    get_qa_history,
    clear_qa_history,
    set_kb_page,
    get_kb_page,
    set_kb_page_size,
    get_kb_page_size,
)

from .api import (
    get_api_client,
    reset_api_client,
    api_login,
    api_register,
    api_request_password_reset,
    api_get_answer,
    api_ingest_document,
    api_get_stats,
    api_list_knowledge,
    api_list_documents,
    api_update_knowledge,
    api_delete_knowledge,
    api_delete_document,
    api_evaluate_qa_batch,
    api_evaluate_custom_question,
    api_evaluate_ingest,
    api_evaluate_custom_file,
    api_get_qa_pairs,
    api_get_ingest_cases,
    api_get_reports,
)

__all__ = [
    # Session
    "init_session_state",
    "save_tokens",
    "save_user_info",
    "clear_auth",
    "set_current_page",
    "is_authenticated",
    "get_api_url",
    "set_api_url",
    "add_qa_history",
    "get_qa_history",
    "clear_qa_history",
    "set_kb_page",
    "get_kb_page",
    "set_kb_page_size",
    "get_kb_page_size",
    # API
    "get_api_client",
    "reset_api_client",
    "api_login",
    "api_register",
    "api_request_password_reset",
    "api_get_answer",
    "api_ingest_document",
    "api_get_stats",
    "api_list_knowledge",
    "api_list_documents",
    "api_update_knowledge",
    "api_delete_knowledge",
    "api_delete_document",
    "api_evaluate_qa_batch",
    "api_evaluate_custom_question",
    "api_evaluate_ingest",
    "api_evaluate_custom_file",
    "api_get_qa_pairs",
    "api_get_ingest_cases",
    "api_get_reports",
]
